#!/bin/bash

python3 -m build
if [ $? -ne 0 ]; then
    echo "Install failed"
    exit 1
fi
pip3 install -e .
if [ $? -ne 0 ]; then
    echo "Install failed"
    exit 1
fi

# Import mplgui. If the version installed is not the most recent then
# this will print a warning to the user.
python3 -c 'import mplgui'
if [ $? -ne 0 ]; then
    exit 1
fi

# Link developer environment things to the .git directory
dev/link_githooks


